description: "Learn about building realtime apps with Theron."

gems:
  - jekyll-assets

markdown: kramdown

collections:
  docs:
    output: true

assets:
  prefix: "/static/assets"

  digest: true

  assets:
    - "*.woff"
