description: "Reactive storage for realtime applications. Theron instantly streams data across clients, so you can focus on creating an extraordinary experience for your users."

markdown: kramdown

permalink: /blog/:title.html

paginate: 5
paginate_path: /blog/page/:num.html

gems:
  - jekyll-assets
  - jekyll-paginate

collections:
  docs:
    output: true
  posts:
    output: true

assets:
  prefix: "/static/assets"

  digest: true

  assets:
    - "*.png"
    - "*.woff"
